# Site settings
title:          Finding solutions
description:    "Solution architecture"
baseurl:        "/"
url:            "https://pdsutcliffe.co.uk"

# Author
author:
  name:         Pete Sutcliffe
  url:          https://pdsutcliffe.co.uk
  email:        

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
